### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/admin#2]
You should have a slide show with the following slides and nothing more:
1. - [ ] An introduction to the team
2. - [ ] A brief description of the project
3. - [ ] A domain model of the project (TripleParity/docs#1)
4. - [ ] The outline of your requirements and design document (TripleParity/docs#6)
5. - [ ] A package diagram of your project (TripleParity/docs#3)
6. - [ ] A deployment diagram of your project (TripleParity/docs#2)

You should also show the following live:
- [ ] Your landing page (#1)
- [ ] Your slack group
- [ ] Your project management (ZenHub, Waffle, Codetree or others )
- [ ] Your git repository
- [ ] Implementation of at least one use case

**Comment by egeldenhuys** [comment]
Currently we will use the diagrams as they are. They might be updated after meeting with the client, hopefully on Wednesday afternoon.

The package diagram I am not sure about.
A description of the project can be extracted from the tender.
Intro to the team can also be extracted from the docs on Google Drive. Perhaps photo, name, degree of study?

**Comment by EmpireMuncher** [comment]
Oh okay, sounds easy. Will shout if I need help.

**Comment by egeldenhuys** [comment]
The Deployment Diagram PNG can be found at [docs/pull/5](https://github.com/TripleParity/docs/pull/5)

**Comment by egeldenhuys** [comment]
Domain Diagram png: TripleParity/docs/pull/7
Package Diagram png: TripleParity/docs/pull/8
